/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 sun.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-22d690373f704f2295d3456288d71ca5
Title: Sun
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/assets/sun/sun.gltf");
  const modelRef = useRef(null); //creating reference to access the DOM element

  useFrame(() => {
    modelRef.current.rotation.y += 0.01; //adding rotation using useFrame hook
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={modelRef}
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
        scale={1.5}
      />
    </group>
  );
}

useGLTF.preload("/assets/sun/sun.gltf");
